---
- project:
    check:
      jobs:
        - run-test-command
        - tox-docs
    third-party-check:
      jobs:
        - run-test-command
    periodic:
      jobs:
        - tox-docs
        - build-sphinx-docs
#        - ansible-otc-lint
#- job:
#    name: ansible-otc-lint
#    pre-run: tests/pre.yml
#    run: tests/run.yml
#    post-run: tests/post.yml
#    attempts: 1
#    timeout: 5400
#    branches: master,zuultrigger
#    required-projects:
#      - openstack/kolla
#      - openstack/requirements
#    irrelevant-files:
#      - ^.*\.rst$
#      - ^doc/.*
#      - ^test-requirements.txt$
#      - ^releasenotes/.*$
#    vars:
#      scenario: aio
#    roles:
#      - zuul: openstack-infra/zuul-jobs
#
